import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateArchiveAndLinkItWithChunk1770561755454 implements MigrationInterface {
    name = 'CreateArchiveAndLinkItWithChunk1770561755454'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TYPE "public"."archive_type" AS ENUM('image', 'file', 'unknown')
        `);
        await queryRunner.query(`
            CREATE TABLE "archive" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "type" "public"."archive_type" NOT NULL,
                "snapshot_id" integer NOT NULL,
                "name" character varying(255) NOT NULL,
                "uuid" uuid,
                "creation" TIMESTAMP WITH TIME ZONE,
                "index_hash_sha256" character varying(64),
                "metadata_creation" TIMESTAMP WITH TIME ZONE DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer DEFAULT '1',
                CONSTRAINT "PK_6493b19677ebfecfcf5281f4233" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_59f91b778d14646b85bfdbceb7" ON "archive" ("snapshot_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_13ed93c2e103ffd15ae78c239d" ON "archive" ("name")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_01973934c13463a204406f9aee" ON "archive" ("creation")
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_ff75ddc41d709f2bdfad094b61" ON "archive" (
                "snapshot_id",
                "type",
                "name",
                "metadata_deletion"
            )
            WHERE "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_f22cefe8110bb95f18241eaf0b" ON "archive" ("snapshot_id", "type", "name")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_5b4b41a76291c5ff6b8fe7ecaa" ON "archive" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4eb9f7bba3b19a9df923cac8f8" ON "archive" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_e25af45a6063e9786a3f0fe7e7" ON "archive" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TABLE "archive_chunk" (
                "archive_id" integer NOT NULL,
                "chunk_id" integer NOT NULL,
                "count" integer NOT NULL DEFAULT '1',
                CONSTRAINT "PK_4543bc3e25c75e890590ff5d110" PRIMARY KEY ("archive_id", "chunk_id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_f43cb66acd2e2919ef09f5e8a1" ON "archive_chunk" ("count")
        `);
        await queryRunner.query(`
            ALTER TABLE "archive"
            ADD CONSTRAINT "FK_59f91b778d14646b85bfdbceb76" FOREIGN KEY ("snapshot_id") REFERENCES "snapshot"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "archive_chunk"
            ADD CONSTRAINT "FK_0f70a0c90f4f2114dcd7544397c" FOREIGN KEY ("archive_id") REFERENCES "archive"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "archive_chunk"
            ADD CONSTRAINT "FK_c14d9db8f4421080e225b28db5d" FOREIGN KEY ("chunk_id") REFERENCES "chunk"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "archive_chunk" DROP CONSTRAINT "FK_c14d9db8f4421080e225b28db5d"
        `);
        await queryRunner.query(`
            ALTER TABLE "archive_chunk" DROP CONSTRAINT "FK_0f70a0c90f4f2114dcd7544397c"
        `);
        await queryRunner.query(`
            ALTER TABLE "archive" DROP CONSTRAINT "FK_59f91b778d14646b85bfdbceb76"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_f43cb66acd2e2919ef09f5e8a1"
        `);
        await queryRunner.query(`
            DROP TABLE "archive_chunk"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_e25af45a6063e9786a3f0fe7e7"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4eb9f7bba3b19a9df923cac8f8"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_5b4b41a76291c5ff6b8fe7ecaa"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_f22cefe8110bb95f18241eaf0b"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_ff75ddc41d709f2bdfad094b61"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_01973934c13463a204406f9aee"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_13ed93c2e103ffd15ae78c239d"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_59f91b778d14646b85bfdbceb7"
        `);
        await queryRunner.query(`
            DROP TABLE "archive"
        `);
        await queryRunner.query(`
            DROP TYPE "public"."archive_type"
        `);
    }

}
