import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1770561207710 implements MigrationInterface {
    name = 'Initial1770561207710'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "host_address" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "host_id" integer NOT NULL,
                "scheme" character varying(31) NOT NULL DEFAULT 'http',
                "user_info" character varying(255),
                "host" character varying(255) NOT NULL DEFAULT 'localhost',
                "path" character varying(1023),
                "active" boolean DEFAULT true,
                "metadata_creation" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer NOT NULL DEFAULT '1',
                CONSTRAINT "REL_fd3f998efdb1906319252389ed" UNIQUE ("host_id"),
                CONSTRAINT "PK_55c2189a1a38971b0a4412ec4f7" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_fd3f998efdb1906319252389ed" ON "host_address" ("host_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_551161938915eaf664b9c6a7dd" ON "host_address" ("scheme")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_b7187b1b3edb2a75cd231abada" ON "host_address" ("user_info")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_8738899695b6c5b6d0f30ec675" ON "host_address" ("host")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_6a3b7d9b0458bd081b01a30116" ON "host_address" ("path")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_650eb530b2ea02cc7a20d5c97c" ON "host_address" ("active")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_bd23b9c0914a64ee28aa513f51" ON "host_address" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_2bab2010e8ed9e916bf1c89b6d" ON "host_address" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_2b17cdf92eae9b74bdfff07c91" ON "host_address" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TABLE "host" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "name" character varying(255) NOT NULL,
                "active" boolean DEFAULT true,
                "address_id" integer,
                "metadata_creation" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer NOT NULL DEFAULT '1',
                CONSTRAINT "REL_55c2189a1a38971b0a4412ec4f" UNIQUE ("address_id"),
                CONSTRAINT "PK_44424c24c2f9b1d7bbf8721f4c4" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_d93daa8d96a567c9904ba53025" ON "host" ("name")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_a9e1b0efaa3c31b8e9f2172813" ON "host" ("active")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_ee15600cc56c0b0e6eb2090a2d" ON "host" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_cec1751409bf63f790be74d4c8" ON "host" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4dbb873c152bda7b7e5fa9f063" ON "host" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TABLE "snapshot" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "group_id" integer NOT NULL,
                "time" TIMESTAMP WITH TIME ZONE NOT NULL,
                "metadata_creation" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer NOT NULL DEFAULT '1',
                CONSTRAINT "PK_47b29c1a6055220b1ebdafdf7b5" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_6d3d2bbb5cc4458db80a90c197" ON "snapshot" ("group_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4a152daf40e1a4ba1ee12299fe" ON "snapshot" ("time")
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_31f7f04d741d346c02cc229fd5" ON "snapshot" ("group_id", "time", "metadata_deletion")
            WHERE "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_8c4833eb7679ca23f3e150dc96" ON "snapshot" ("group_id", "time")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_7225afe42936386b5b542b09ff" ON "snapshot" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_6a27ce610e9d6924a21774c98e" ON "snapshot" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_ede17e1ce1779548985007ab1c" ON "snapshot" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TYPE "public"."backup_type" AS ENUM('vm', 'ct', 'host')
        `);
        await queryRunner.query(`
            CREATE TABLE "group" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "datastore_id" integer NOT NULL,
                "namespace_id" integer,
                "type" "public"."backup_type" NOT NULL,
                "backup_id" character varying(255) NOT NULL,
                "metadata_creation" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer NOT NULL DEFAULT '1',
                CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_03adb351f4c2393a46224cfa2a" ON "group" ("datastore_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_9b0c1c4d01025a65a9145abaae" ON "group" ("namespace_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4d1c4ed0c7ea9a8a127b0b50f8" ON "group" ("backup_id")
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_a8f1e9f90149cf735ba8eda59f" ON "group" (
                "datastore_id",
                "namespace_id",
                "type",
                "backup_id",
                "metadata_deletion"
            )
            WHERE "namespace_id" IS NOT NULL
                AND "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_71f66026f61527204baec18663" ON "group" (
                "datastore_id",
                "type",
                "backup_id",
                "metadata_deletion"
            )
            WHERE "namespace_id" IS NULL
                AND "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_50346f3e0119a8a66e108be9a1" ON "group" (
                "datastore_id",
                "namespace_id",
                "type",
                "backup_id"
            )
            WHERE "namespace_id" IS NOT NULL
                AND "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_47c20d9e321e164b1322b4329b" ON "group" ("datastore_id", "type", "backup_id")
            WHERE "namespace_id" IS NULL
                AND "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_41f9da3d0f41807ef06ce43b18" ON "group" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_b1e789b69de6def23ddc0869d0" ON "group" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_ce3da12bf7c598115a6872f00b" ON "group" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TABLE "chunk" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "datastore_id" integer NOT NULL,
                "hash_sha256" character varying(64) NOT NULL,
                "unused" boolean NOT NULL DEFAULT false,
                "size_bytes" bigint,
                "metadata_creation" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer NOT NULL DEFAULT '1',
                CONSTRAINT "PK_444ba832a2c514629d265d81b5f" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_e71fe82e32c4ab0aa51327d602" ON "chunk" ("datastore_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_22c101223bb90c9d0fbea0e594" ON "chunk" ("hash_sha256")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_5e22a991f6743dfdcc3d7b9104" ON "chunk" ("unused")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_481bf653d29ddc6451651ee4ee" ON "chunk" ("size_bytes")
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_3521fb5577ba513bc924c8d40f" ON "chunk" (
                "datastore_id",
                "hash_sha256",
                "metadata_deletion"
            )
            WHERE "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_388fac50b35877846012f647e4" ON "chunk" ("datastore_id", "hash_sha256")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4ee600e98a1648109edf272b2b" ON "chunk" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_a4a1330cdc0951510c2d2ef40b" ON "chunk" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_51ab4e725b02f38209e9c94296" ON "chunk" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TABLE "datastore" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "host_id" integer,
                "name" character varying(255) NOT NULL,
                "mountpoint" character varying(255),
                "metadata_creation" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer NOT NULL DEFAULT '1',
                CONSTRAINT "PK_6c9c43d8c7123cb7c960ba2c290" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_5b06f26fa25006b4417216ff24" ON "datastore" ("host_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4713a9a600985e991166bcd933" ON "datastore" ("name")
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_9b63099613b6d2ce33cb7fdc01" ON "datastore" ("host_id", "name", "metadata_deletion")
            WHERE "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_17df6082537116ada02719f9e2" ON "datastore" ("host_id", "name")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_a18fd453aecd1d9a4dfa236c9f" ON "datastore" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_1259084703b25f8b17bec1462a" ON "datastore" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_d2e54264c8f31442ef3599ff02" ON "datastore" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TABLE "namespace" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "datastore_id" integer NOT NULL,
                "parent_id" integer,
                "name" character varying(255) NOT NULL,
                "metadata_creation" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer NOT NULL DEFAULT '1',
                CONSTRAINT "PK_155557f16b1d166388d7308086a" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_2c54b004ae3c23bdbf7795d599" ON "namespace" ("datastore_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_ba9de2a3719c852c66df9c590d" ON "namespace" ("parent_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_011e61f2ca9be1b10640bc4227" ON "namespace" ("name")
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_f99c8799458b781b70d29dbc4d" ON "namespace" (
                "datastore_id",
                "parent_id",
                "name",
                "metadata_deletion"
            )
            WHERE "parent_id" IS NOT NULL
                AND "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_a6b99fee5f2f121cb5da578619" ON "namespace" ("datastore_id", "name", "metadata_deletion")
            WHERE "parent_id" IS NULL
                AND "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_01c1f194d7927ebf4dd6dc4e1f" ON "namespace" ("datastore_id", "parent_id", "name")
            WHERE "parent_id" IS NOT NULL
                AND "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_3a4cc68a95461d1d8351135577" ON "namespace" ("datastore_id", "name")
            WHERE "parent_id" IS NULL
                AND "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_f0dd7bbcdc168a292468096127" ON "namespace" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_fde31c14384304e40c2e8af123" ON "namespace" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_47fba5602a5064b470af14990a" ON "namespace" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TABLE "namespace_closure" (
                "id_ancestor" integer NOT NULL,
                "id_descendant" integer NOT NULL,
                CONSTRAINT "PK_d92fa36e11ec8e16f3a2a7852f7" PRIMARY KEY ("id_ancestor", "id_descendant")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_56b1595ab5300280387dc05b21" ON "namespace_closure" ("id_ancestor")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_c39cb1446cc05ea3062af02b9f" ON "namespace_closure" ("id_descendant")
        `);
        await queryRunner.query(`
            ALTER TABLE "host_address"
            ADD CONSTRAINT "FK_fd3f998efdb1906319252389edc" FOREIGN KEY ("host_id") REFERENCES "host"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            ALTER TABLE "host"
            ADD CONSTRAINT "FK_55c2189a1a38971b0a4412ec4f7" FOREIGN KEY ("address_id") REFERENCES "host_address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            ALTER TABLE "snapshot"
            ADD CONSTRAINT "FK_6d3d2bbb5cc4458db80a90c197f" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "group"
            ADD CONSTRAINT "FK_03adb351f4c2393a46224cfa2a5" FOREIGN KEY ("datastore_id") REFERENCES "datastore"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "group"
            ADD CONSTRAINT "FK_9b0c1c4d01025a65a9145abaae9" FOREIGN KEY ("namespace_id") REFERENCES "namespace"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "chunk"
            ADD CONSTRAINT "FK_e71fe82e32c4ab0aa51327d6023" FOREIGN KEY ("datastore_id") REFERENCES "datastore"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "datastore"
            ADD CONSTRAINT "FK_5b06f26fa25006b4417216ff241" FOREIGN KEY ("host_id") REFERENCES "host"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "namespace"
            ADD CONSTRAINT "FK_2c54b004ae3c23bdbf7795d599c" FOREIGN KEY ("datastore_id") REFERENCES "datastore"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "namespace"
            ADD CONSTRAINT "FK_ba9de2a3719c852c66df9c590d9" FOREIGN KEY ("parent_id") REFERENCES "namespace"("id") ON DELETE NO ACTION ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            ALTER TABLE "namespace_closure"
            ADD CONSTRAINT "FK_56b1595ab5300280387dc05b21d" FOREIGN KEY ("id_ancestor") REFERENCES "namespace"("id") ON DELETE CASCADE ON UPDATE NO ACTION
        `);
        await queryRunner.query(`
            ALTER TABLE "namespace_closure"
            ADD CONSTRAINT "FK_c39cb1446cc05ea3062af02b9fe" FOREIGN KEY ("id_descendant") REFERENCES "namespace"("id") ON DELETE CASCADE ON UPDATE NO ACTION
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "namespace_closure" DROP CONSTRAINT "FK_c39cb1446cc05ea3062af02b9fe"
        `);
        await queryRunner.query(`
            ALTER TABLE "namespace_closure" DROP CONSTRAINT "FK_56b1595ab5300280387dc05b21d"
        `);
        await queryRunner.query(`
            ALTER TABLE "namespace" DROP CONSTRAINT "FK_ba9de2a3719c852c66df9c590d9"
        `);
        await queryRunner.query(`
            ALTER TABLE "namespace" DROP CONSTRAINT "FK_2c54b004ae3c23bdbf7795d599c"
        `);
        await queryRunner.query(`
            ALTER TABLE "datastore" DROP CONSTRAINT "FK_5b06f26fa25006b4417216ff241"
        `);
        await queryRunner.query(`
            ALTER TABLE "chunk" DROP CONSTRAINT "FK_e71fe82e32c4ab0aa51327d6023"
        `);
        await queryRunner.query(`
            ALTER TABLE "group" DROP CONSTRAINT "FK_9b0c1c4d01025a65a9145abaae9"
        `);
        await queryRunner.query(`
            ALTER TABLE "group" DROP CONSTRAINT "FK_03adb351f4c2393a46224cfa2a5"
        `);
        await queryRunner.query(`
            ALTER TABLE "snapshot" DROP CONSTRAINT "FK_6d3d2bbb5cc4458db80a90c197f"
        `);
        await queryRunner.query(`
            ALTER TABLE "host" DROP CONSTRAINT "FK_55c2189a1a38971b0a4412ec4f7"
        `);
        await queryRunner.query(`
            ALTER TABLE "host_address" DROP CONSTRAINT "FK_fd3f998efdb1906319252389edc"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_c39cb1446cc05ea3062af02b9f"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_56b1595ab5300280387dc05b21"
        `);
        await queryRunner.query(`
            DROP TABLE "namespace_closure"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_47fba5602a5064b470af14990a"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_fde31c14384304e40c2e8af123"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_f0dd7bbcdc168a292468096127"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_3a4cc68a95461d1d8351135577"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_01c1f194d7927ebf4dd6dc4e1f"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_a6b99fee5f2f121cb5da578619"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_f99c8799458b781b70d29dbc4d"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_011e61f2ca9be1b10640bc4227"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_ba9de2a3719c852c66df9c590d"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_2c54b004ae3c23bdbf7795d599"
        `);
        await queryRunner.query(`
            DROP TABLE "namespace"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_d2e54264c8f31442ef3599ff02"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_1259084703b25f8b17bec1462a"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_a18fd453aecd1d9a4dfa236c9f"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_17df6082537116ada02719f9e2"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_9b63099613b6d2ce33cb7fdc01"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4713a9a600985e991166bcd933"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_5b06f26fa25006b4417216ff24"
        `);
        await queryRunner.query(`
            DROP TABLE "datastore"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_51ab4e725b02f38209e9c94296"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_a4a1330cdc0951510c2d2ef40b"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4ee600e98a1648109edf272b2b"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_388fac50b35877846012f647e4"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_3521fb5577ba513bc924c8d40f"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_481bf653d29ddc6451651ee4ee"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_5e22a991f6743dfdcc3d7b9104"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_22c101223bb90c9d0fbea0e594"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_e71fe82e32c4ab0aa51327d602"
        `);
        await queryRunner.query(`
            DROP TABLE "chunk"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_ce3da12bf7c598115a6872f00b"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_b1e789b69de6def23ddc0869d0"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_41f9da3d0f41807ef06ce43b18"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_47c20d9e321e164b1322b4329b"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_50346f3e0119a8a66e108be9a1"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_71f66026f61527204baec18663"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_a8f1e9f90149cf735ba8eda59f"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4d1c4ed0c7ea9a8a127b0b50f8"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_9b0c1c4d01025a65a9145abaae"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_03adb351f4c2393a46224cfa2a"
        `);
        await queryRunner.query(`
            DROP TABLE "group"
        `);
        await queryRunner.query(`
            DROP TYPE "public"."backup_type"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_ede17e1ce1779548985007ab1c"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_6a27ce610e9d6924a21774c98e"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_7225afe42936386b5b542b09ff"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_8c4833eb7679ca23f3e150dc96"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_31f7f04d741d346c02cc229fd5"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4a152daf40e1a4ba1ee12299fe"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_6d3d2bbb5cc4458db80a90c197"
        `);
        await queryRunner.query(`
            DROP TABLE "snapshot"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4dbb873c152bda7b7e5fa9f063"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_cec1751409bf63f790be74d4c8"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_ee15600cc56c0b0e6eb2090a2d"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_a9e1b0efaa3c31b8e9f2172813"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_d93daa8d96a567c9904ba53025"
        `);
        await queryRunner.query(`
            DROP TABLE "host"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_2b17cdf92eae9b74bdfff07c91"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_2bab2010e8ed9e916bf1c89b6d"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_bd23b9c0914a64ee28aa513f51"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_650eb530b2ea02cc7a20d5c97c"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_6a3b7d9b0458bd081b01a30116"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_8738899695b6c5b6d0f30ec675"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_b7187b1b3edb2a75cd231abada"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_551161938915eaf664b9c6a7dd"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_fd3f998efdb1906319252389ed"
        `);
        await queryRunner.query(`
            DROP TABLE "host_address"
        `);
    }

}
