import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateSSHConnectionAndSSHKeypair1770563892448 implements MigrationInterface {
    name = 'CreateSSHConnectionAndSSHKeypair1770563892448'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "ssh_connection" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "name" character varying(255) NOT NULL,
                "host" character varying(255) NOT NULL,
                "port" integer DEFAULT '22',
                "username" character varying(255) NOT NULL,
                "ssh_keypair_id" integer NOT NULL,
                "active" boolean DEFAULT true,
                "metadata_creation" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer NOT NULL DEFAULT '1',
                CONSTRAINT "PK_624264f635674c3a044ae088366" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_ba77a95f668715e84a4e96a4ca" ON "ssh_connection" ("name")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_0f149f1b4f91a29dc93f865939" ON "ssh_connection" ("host")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4a1693710795e6eebae6624eaf" ON "ssh_connection" ("port")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_cb38efdd76ed3ca18e3cfbddb8" ON "ssh_connection" ("username")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_c1f613a8d68bdb1e175792aa6f" ON "ssh_connection" ("ssh_keypair_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_b0920281c5a524e6d7349ea201" ON "ssh_connection" ("active")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_72cadc9302d6bc3df9708a4270" ON "ssh_connection" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4d478ef70f607dbf2e244cc16d" ON "ssh_connection" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_e11a6502b5a948e696f0343925" ON "ssh_connection" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TYPE "public"."ssh_key_algorithm" AS ENUM('dsa', 'rsa', 'ecdsa', 'ed25519', 'curve25519')
        `);
        await queryRunner.query(`
            CREATE TYPE "public"."ssh_key_fingerprint_hash_algorithm" AS ENUM('sha1', 'sha256', 'sha384', 'sha512', 'md5')
        `);
        await queryRunner.query(`
            CREATE TYPE "public"."ssh_private_key_format" AS ENUM(
                'pem',
                'pkcs1',
                'pkcs8',
                'rfc4253',
                'ssh',
                'ssh-private',
                'openssh',
                'dnssec'
            )
        `);
        await queryRunner.query(`
            CREATE TYPE "public"."ssh_public_key_format" AS ENUM(
                'pem',
                'pkcs1',
                'pkcs8',
                'rfc4253',
                'ssh',
                'ssh-private',
                'openssh',
                'dnssec',
                'putty',
                'ppk'
            )
        `);
        await queryRunner.query(`
            CREATE TABLE "ssh_keypair" (
                "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "name" character varying(255) NOT NULL,
                "algorithm" "public"."ssh_key_algorithm",
                "fingerprint_hash_algorithm" "public"."ssh_key_fingerprint_hash_algorithm",
                "fingerprint_hash" bytea,
                "fingerprint" bytea,
                "private_key_file" character varying(255),
                "public_key_file" character varying(255),
                "private_key_format" "public"."ssh_private_key_format",
                "private_key" bytea,
                "public_key_format" "public"."ssh_public_key_format",
                "public_key" bytea,
                "active" boolean DEFAULT true,
                "metadata_creation" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "metadata_deletion" TIMESTAMP WITH TIME ZONE,
                "metadata_version" integer NOT NULL DEFAULT '1',
                CONSTRAINT "PK_f71de5e4926cb847ebf60f9bb3b" PRIMARY KEY ("id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_c9b6f1aa0fe6e9ced59af00659" ON "ssh_keypair" ("name")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_d42454b557d3a7770ade9dfcbc" ON "ssh_keypair" ("algorithm")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4cb6820a4577f694e0ee3a5cf9" ON "ssh_keypair" ("fingerprint_hash_algorithm")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_1fb2811618d1972d656e4d4fb4" ON "ssh_keypair" ("fingerprint_hash")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_672046cde3fe59e3e7aa00a5f9" ON "ssh_keypair" ("fingerprint")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_a031da1f88fc437ea78ffa7517" ON "ssh_keypair" ("private_key_file")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_14a20b691e6bd752f6eff50b94" ON "ssh_keypair" ("public_key_file")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_525ac2ff596198f17d6b714824" ON "ssh_keypair" ("private_key_format")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_9af839c4fd3dd9ceb3ba9d4dcd" ON "ssh_keypair" ("private_key")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_4580993e904b093ca015f961de" ON "ssh_keypair" ("public_key_format")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_3307c98026b6f566aeda9d9a2f" ON "ssh_keypair" ("public_key")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_51b044650641b64bad1bd7896c" ON "ssh_keypair" ("active")
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_8418d675d8aaf8aaeb0a8895a5" ON "ssh_keypair" ("name", "algorithm", "metadata_deletion")
            WHERE "algorithm" IS NOT NULL
                AND "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_7708f9685440b0d54c3bb8c923" ON "ssh_keypair" ("name", "metadata_deletion")
            WHERE "algorithm" IS NULL
                AND "metadata_deletion" IS NOT NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_f79f63b234b74e3ef7d4a0ae20" ON "ssh_keypair" ("name", "algorithm")
            WHERE "algorithm" IS NOT NULL
                AND "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE UNIQUE INDEX "IDX_8d0c1801caa8d63a0425d252d7" ON "ssh_keypair" ("name")
            WHERE "algorithm" IS NULL
                AND "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_87ecf2af9b90f618ad20b0ea21" ON "ssh_keypair" ("metadata_creation")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_1dc398a83b59eea50817cbbc7a" ON "ssh_keypair" ("metadata_update")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_6cb00b61b74dce48bcdd0e1c1d" ON "ssh_keypair" ("metadata_deletion")
            WHERE "metadata_deletion" IS NULL
        `);
        await queryRunner.query(`
            CREATE TABLE "ssh_connection_remote_host_keys" (
                "ssh_connection_id" integer NOT NULL,
                "ssh_keypair_id" integer NOT NULL,
                CONSTRAINT "PK_386679d055f7d3429b6f070015f" PRIMARY KEY ("ssh_connection_id", "ssh_keypair_id")
            )
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_268d73da8cd0079c9eac5a6d62" ON "ssh_connection_remote_host_keys" ("ssh_connection_id")
        `);
        await queryRunner.query(`
            CREATE INDEX "IDX_cd19c69e404ac721f4d2e4fcbf" ON "ssh_connection_remote_host_keys" ("ssh_keypair_id")
        `);
        await queryRunner.query(`
            ALTER TABLE "ssh_connection"
            ADD CONSTRAINT "FK_c1f613a8d68bdb1e175792aa6f3" FOREIGN KEY ("ssh_keypair_id") REFERENCES "ssh_keypair"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "ssh_connection_remote_host_keys"
            ADD CONSTRAINT "FK_268d73da8cd0079c9eac5a6d62e" FOREIGN KEY ("ssh_connection_id") REFERENCES "ssh_connection"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
        await queryRunner.query(`
            ALTER TABLE "ssh_connection_remote_host_keys"
            ADD CONSTRAINT "FK_cd19c69e404ac721f4d2e4fcbf9" FOREIGN KEY ("ssh_keypair_id") REFERENCES "ssh_keypair"("id") ON DELETE CASCADE ON UPDATE CASCADE
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            ALTER TABLE "ssh_connection_remote_host_keys" DROP CONSTRAINT "FK_cd19c69e404ac721f4d2e4fcbf9"
        `);
        await queryRunner.query(`
            ALTER TABLE "ssh_connection_remote_host_keys" DROP CONSTRAINT "FK_268d73da8cd0079c9eac5a6d62e"
        `);
        await queryRunner.query(`
            ALTER TABLE "ssh_connection" DROP CONSTRAINT "FK_c1f613a8d68bdb1e175792aa6f3"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_cd19c69e404ac721f4d2e4fcbf"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_268d73da8cd0079c9eac5a6d62"
        `);
        await queryRunner.query(`
            DROP TABLE "ssh_connection_remote_host_keys"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_6cb00b61b74dce48bcdd0e1c1d"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_1dc398a83b59eea50817cbbc7a"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_87ecf2af9b90f618ad20b0ea21"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_8d0c1801caa8d63a0425d252d7"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_f79f63b234b74e3ef7d4a0ae20"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_7708f9685440b0d54c3bb8c923"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_8418d675d8aaf8aaeb0a8895a5"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_51b044650641b64bad1bd7896c"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_3307c98026b6f566aeda9d9a2f"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4580993e904b093ca015f961de"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_9af839c4fd3dd9ceb3ba9d4dcd"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_525ac2ff596198f17d6b714824"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_14a20b691e6bd752f6eff50b94"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_a031da1f88fc437ea78ffa7517"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_672046cde3fe59e3e7aa00a5f9"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_1fb2811618d1972d656e4d4fb4"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4cb6820a4577f694e0ee3a5cf9"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_d42454b557d3a7770ade9dfcbc"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_c9b6f1aa0fe6e9ced59af00659"
        `);
        await queryRunner.query(`
            DROP TABLE "ssh_keypair"
        `);
        await queryRunner.query(`
            DROP TYPE "public"."ssh_public_key_format"
        `);
        await queryRunner.query(`
            DROP TYPE "public"."ssh_private_key_format"
        `);
        await queryRunner.query(`
            DROP TYPE "public"."ssh_key_fingerprint_hash_algorithm"
        `);
        await queryRunner.query(`
            DROP TYPE "public"."ssh_key_algorithm"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_e11a6502b5a948e696f0343925"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4d478ef70f607dbf2e244cc16d"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_72cadc9302d6bc3df9708a4270"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_b0920281c5a524e6d7349ea201"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_c1f613a8d68bdb1e175792aa6f"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_cb38efdd76ed3ca18e3cfbddb8"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_4a1693710795e6eebae6624eaf"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_0f149f1b4f91a29dc93f865939"
        `);
        await queryRunner.query(`
            DROP INDEX "public"."IDX_ba77a95f668715e84a4e96a4ca"
        `);
        await queryRunner.query(`
            DROP TABLE "ssh_connection"
        `);
    }

}
